name: Game Manager To GIST

on: [push]

jobs:
  GameManagerToGist:
    name: GameManagerToGist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/TaeSSuB/f2947717de8f34e37f8a24f12a2550ca
          gist_title: GameManager.cs
          github_file: HammerLike/Assets/WorkSpace/Scripts/Managers/GameManager.cs