name: Upload CS Files to Gist

on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/TaeSSuB/fdc6f54e047730dc849618ab858d7062
          gist_title: Example Gist Title
          gist_description: Example Gist Description
          github_file: filename-to-sync