name: Create Gist on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install @octokit/core

      - name: List CS Files
        run: |
          find HammerLike/Assets/WorkSpace/Scripts/Base -type f -name '*.cs' > files.txt

      - name: Create Gists
        id: create_gists
        run: |
          const fs = require('fs');
          const { Octokit } = require('@octokit/core');
          const fileList = fs.readFileSync('files.txt', 'utf-8').split('\n').filter(Boolean);
          const octo = new Octokit({ auth: process.env.GITHUB_TOKEN });
          const gistPromises = fileList.map(file => {
            const content = fs.readFileSync(file, 'utf-8');
            return octo.request('POST /gists', {
              description: `Gist created by GitHub Actions for ${file}`,
              public: true,
              files: {
                [`${file.split('/').pop()}.txt`]: {
                  content: content
                }
              }
            });
          });
          Promise.all(gistPromises).then(gists => {
            console.log('Gists created:');
            gists.forEach(gist => console.log(gist.data.html_url));
          }).catch(error => {
            console.error('Error creating Gists: ', error);
            process.exit(1);
          });