name: Upload CS Files to Gist

on:
  push:
    paths:
      - 'HammerLike/Assets/WorkSpace/Scripts/Base/*.cs'

jobs:
  upload_to_gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Upload files to Gist
      uses: gistsync/github-action@v2
      with:
        gist_id: 'TaeSSuB'
        GITHUB_TOKEN: ${{ secrets.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 }}
        file_path: 'HammerLike/Assets/WorkSpace/Scripts/Base/*.cs'