name: Upload CS Files to Gist

on: 
  push:
    paths:
      - 'HammerLike/Assets/WorkSpace/Scripts/Base/*.cs'

jobs:
  upload-to-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests module
        run: pip install requests

      - name: Upload files to Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST }}
          GIST_ID: 'TaeSSuB'
        run: |
          import os
          import requests

          api_url = "https://api.github.com/gists"
          headers = {
            "Authorization": f"token {os.getenv('GIST')}"
          }

          files = {}
          for filename in os.listdir('HammerLike/Assets/WorkSpace/Scripts/Base'):
            if filename.endswith('.cs'):
              path = f'HammerLike/Assets/WorkSpace/Scripts/Base/{filename}'
              with open(path, 'r') as file:
                files[filename] = {"content": file.read()}

          gist_data = {
            "files": files,
            "description": "Auto-updated CS files",
            "public": False
          }

          response = requests.patch(f"{api_url}/{os.getenv('GIST_ID')}", headers=headers, json=gist_data)
          print(response.json())