name: Upload CS Files to Gist

on:
  push:
    paths:
      - 'HammerLike/Assets/WorkSpace/Scripts/Base/*.cs'

jobs:
  upload_to_gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload .cs files to Gist
      env:
        GITHUB_TOKEN: ${{ secrets.GIST }}
        GIST_ID: 'TaeSSuB'  # Replace with your actual Gist ID
      run: |
        #!/bin/bash
        API_URL="https://api.github.com/gists/TaeSSuB"
        FILES_TO_UPLOAD=""

        # Collecting .cs files
        for FILE in $(find HammerLike/Assets/WorkSpace/Scripts/Base/ -type f -name '*.cs'); do
          FILE_CONTENT=$(cat "$FILE")
          # Prepare JSON data for API
          FILE_BASENAME=$(basename "$FILE")
          FILE_JSON_PART=$(jq -n --arg name "$FILE_BASENAME" --arg content "$FILE_CONTENT" \
            '{($name): {"content": $content}}')
          FILES_TO_UPLOAD=$(echo "$FILES_TO_UPLOAD $FILE_JSON_PART" | jq -s add)
        done

        # Create JSON payload
        JSON_PAYLOAD=$(jq -n --argjson files "$FILES_TO_UPLOAD" '{"files": $files}')

        # Update the Gist
        RESPONSE=$(curl -s -X PATCH "$API_URL" -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" -d "$JSON_PAYLOAD")

        if echo "$RESPONSE" | jq -e '.message' > /dev/null; then
          echo "Failed to update Gist. Response: $RESPONSE"
          exit 1
        else
          echo "Gist updated successfully."
        fi

      shell: bash