name: Upload CS Files to Gist

on:
  push:
    paths:
      - 'HammerLike/Assets/WorkSpace/Scripts/Base/*.cs'
  workflow_dispatch:  # Enables manual trigger through GitHub UI

jobs:
  upload_to_gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Upload Files to Gist
        env:
          GIST_ID: 'TaeSSuB'  # Make sure to replace this with your actual Gist ID if needed
          GIST_TOKEN: ${{ secrets.GIST }}
        run: |
          FILES=""
          for FILE in HammerLike/Assets/WorkSpace/Scripts/Base/*.cs; do
            CONTENT=$(<"$FILE")
            JSON_CONTENT=$(jq -aRs . <<< "$CONTENT")
            FILES+=\"$(basename "$FILE")\": {\"content\": $JSON_CONTENT},
          done
          JSON="{\"files\": {${FILES%?}}}"

          curl -H "Authorization: token $GIST" \
               -X PATCH \
               "https://api.github.com/gists/$GIST_ID" \
               -d "$JSON"